export const BOOK_NAME_TO_SLUG: Record<string, string> = {
  // Ancien Testament
  'Genèse': 'genese',
  'Genése': 'genese',
  'Exode': 'exode',
  'Lévitique': 'levitique',
  'Nombres': 'nombres',
  'Deutéronome': 'deuteronome',
  'Josué': 'josue',
  'Juges': 'juges',
  'Ruth': 'ruth',
  '1 Samuel': '1-samuel',
  '2 Samuel': '2-samuel',
  '1 Rois': '1-rois',
  '2 Rois': '2-rois',
  '1 Chroniques': '1-chroniques',
  '2 Chroniques': '2-chroniques',
  'Esdras': 'esdras',
  'Néhémie': 'nehemie',
  'Tobie': 'tobie',
  'Judith': 'judith',
  'Esther': 'esther',
  '1 Maccabées': '1-maccabees',
  '2 Maccabées': '2-maccabees',
  'Job': 'job',
  'Psaumes': 'psaumes',
  'Proverbes': 'proverbes',
  'Ecclésiaste': 'ecclesiaste',
  'Cantique': 'cantique',
  'Sagesse': 'sagesse',
  'Siracide': 'siracide',
  'Isaïe': 'isaie',
  'Jérémie': 'jeremie',
  'Lamentations': 'lamentations',
  'Baruch': 'baruch',
  'Ézéchiel': 'ezechiel',
  'Daniel': 'daniel',
  'Osée': 'osee',
  'Joël': 'joel',
  'Amos': 'amos',
  'Abdias': 'abdias',
  'Jonas': 'jonas',
  'Michée': 'michee',
  'Nahum': 'nahum',
  'Habacuc': 'habacuc',
  'Sophonie': 'sophonie',
  'Aggée': 'aggee',
  'Zacharie': 'zacharie',
  'Malachie': 'malachie',
  // Nouveau Testament
  'Matthieu': 'matthieu',
  'Marc': 'marc',
  'Luc': 'luc',
  'Jean': 'jean',
  'Actes': 'actes',
  'Romains': 'romains',
  '1 Corinthiens': '1-corinthiens',
  '2 Corinthiens': '2-corinthiens',
  'Galates': 'galates',
  'Éphésiens': 'ephesiens',
  'Philippiens': 'philippiens',
  'Colossiens': 'colossiens',
  '1 Thessaloniciens': '1-thessaloniciens',
  '2 Thessaloniciens': '2-thessaloniciens',
  '1 Timothée': '1-timothee',
  '2 Timothée': '2-timothee',
  'Tite': 'tite',
  'Philémon': 'philemon',
  'Hébreux': 'hebreux',
  'Jacques': 'jacques',
  '1 Pierre': '1-pierre',
  '2 Pierre': '2-pierre',
  '1 Jean': '1-jean',
  '2 Jean': '2-jean',
  '3 Jean': '3-jean',
  'Jude': 'jude',
  'Apocalypse': 'apocalypse',
}

export function parseVerseRef(ref: string): { slug: string; chapter: number; verse: number } | null {
  // Format: "Genèse 1:1" ou "1 Samuel 3:4"
  const match = ref.match(/^(.+?)\s+(\d+):(\d+)$/)
  if (!match) return null
  const [, bookName, chapter, verse] = match
  const slug = BOOK_NAME_TO_SLUG[bookName.trim()]
  if (!slug) return null
  return { slug, chapter: Number(chapter), verse: Number(verse) }
}